### Movie Index
GET http://localhost:3000/movies.json
### Movie Show
GET http://localhost:3000/movie/2.json
### Movie Create
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "testmovie",
  "year": "1800",
  "english": "true"
}

### Movie Update
PATCH http://localhost:3000/movie/2.json
Content-Type: application/json

{
  "plot": "A young man named Clark Kent discovers his alien heritage and decides to use his mighty powers for the good of all",
  "director": "Richard Donner",
  "english": "true"
}

### Movie Destroy 
DELETE http://localhost:3000/movie/3.json

### Actors Index
GET http://localhost:3000/actors.json

### Actor Destroy
DELETE http://localhost:3000/actor/5.json

### Actor Create
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Mark",
  "last_name": "Hamill",
  "known_for": "Star Wars",
  "age": 70,
  "gender": "male"

}

### Actor Update
PATCH http://localhost:3000/actor/6.json
Content-Type: application/json

{
  "first_name": "Christopher",
  "age": 52,
  "gender": "male"
}

### Actor Show 
GET http://localhost:3000/actor/8.json
